[tools]
remodel = {source = "rojo-rbx/remodel", version = "0.7.1"}
rojo = {source = "rojo-rbx/rojo", version = "6.0.2"}
tarmac = {source = "jeparlefrancais/tarmac", version = "0.7.1"}
testez = {source = "Roblox/testez", version = "0.2.0"}